### ISSUE TITLE
Maven failure on application

### ISSUE THREAD

**Issue by aabinks** [gertvv/oops#2]
Not sure if this is still in active dev/maintenance, but I get the following error when I run 'mvn package' in the 'application' directory. Also tried 'mvn install'
[ERROR] Failed to execute goal on project oops: Could not resolve dependencies for project nl.rug.ai.mas:oops:jar:0.6.4: Failed to collect dependencies at nl.rug.ai.mas:oops-parser:jar:0.6: Failed to read artifact descriptor for nl.rug.ai.mas:oops-parser:jar:0.6: Failure to find nl.rug.ai.mas:oops-pom:pom:0.6.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I'm running osx 10.9.5, java 1.7.0_71, Maven 3.2.5

I'd be happy to just get a precompiled jar of this code, but I can't find where the download link is (referenced in the README).

**Comment by gertvv** [comment]
Hi aabinks,

Thanks for your interest. I do still maintain OOPS, but at a very low activity level. The README is out of date. You should run "mvn package" in the root directory of the repository instead of from the individual module directories.

We used to offer binaries from the github downloads page, but that functionality was discontinued by github.

I should also point out that a much improved version is available from the "extensions" branch. (I have updated the README on this branch.) This incorporates work by several students to extend OOPS to a bunch of other axiom systems. The user interface has also been improved a lot. The only reason it hasn't been released yet is that I suspect countermodel construction is broken for certain logics (those with the serial relation type). I have been waiting for feedback on that issue. Thanks for reminding me about this project, I'll see if I can get it fixed & released soonish. Please bug me if I don't.

Gert

**Comment by aabinks** [comment]
Thank you Gert! I switched to the extensions branch, ran the install instructions in the README (also the same as your post above) and it built successfully. Looking forward to using it now. Thanks for the pointers!
Adam
